name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  bun:
    uses: Glyndor/.github/.github/workflows/bun-ci.yml@7099f8a9c8be91fa1732fe2402268b338771233f # v1.10.1
    with:
      coverage-threshold: 90
