name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  bun:
    uses: Glyndor/.github/.github/workflows/bun-ci.yml@3a46ffe91ecadcce7f14c99ea8b23ead4274f325 # v1.13.2
    with:
      coverage-threshold: 90
