name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  bun:
    uses: Glyndor/.github/.github/workflows/bun-ci.yml@d5041b038b7d4935e75400dff612962e6fa14893 # v1.21.0
    with:
      coverage-threshold: 90
  pin-policy:
    uses: Glyndor/.github/.github/workflows/pin-policy-reusable.yml@d4bbc5b6ec0c351ca4cb17d948ceaad818da4078 # v1.18.1
  dependabot-freshness:
    uses: Glyndor/.github/.github/workflows/dependabot-freshness.yml@d4bbc5b6ec0c351ca4cb17d948ceaad818da4078 # v1.18.1
    with:
      max-age-days: 15
