name: DCO

on:
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  dco:
    uses: Glyndor/.github/.github/workflows/dco.yml@fadfbebc989a58a2292438fecbd5a616ffa0bdf3 # v1.15.0
