name: DCO

on:
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  dco:
    uses: Glyndor/.github/.github/workflows/dco.yml@c958978687af37dc2d826a967d9c549589afb39f # v1.14.1
