name: Line limit

on:
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  line-limit:
    uses: Glyndor/.github/.github/workflows/line-limit.yml@7099f8a9c8be91fa1732fe2402268b338771233f # v1.10.1
