name: Line limit

on:
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  line-limit:
    uses: Glyndor/.github/.github/workflows/line-limit.yml@e61aaf0e920345b3dbb82cacd3bd36a499951a92 # v1.13.0
