name: guard

on:
  pull_request:
    branches: ["main"]

permissions: {}

jobs:
  develop-only:
    uses: Glyndor/.github/.github/workflows/main-guard.yml@045903bf83a58651f119bc7d952aa45242b897c5 # v1.12.0
